### ISSUE TITLE
Reject empty edits

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#113]
Problem: As a reviewer one regularly faces edits where nothing has been changed (i.e. people just get into the editor and exit by sumbitting a new version). Checking this, then rejecting the edit and giving feedback to the author is time consuming. 

Proposition: An edit is not accepted when content has not been altered at all.

**Comment by inyono** [comment]
This should already be the case in the new editor

**Comment by yolo-bird** [comment]
That's true. I just tested it on an exercise.

**Comment by Knorrke** [comment]
@yolo-bird: note: I think this happens when someone converts an entity from old editor to new editor without changing anything else. Then the revision will show no changes. If you encounter the problem again, and thats not the reason please let us know (e.g. post the link here) because that shouldn't happen
