### ISSUE TITLE
CSRF error when saving static pages (new editor)

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#116]
While updating serlo.org/jobs Simon got today the following error:

![image](https://user-images.githubusercontent.com/1327215/69375687-34057280-0ca9-11ea-83d4-67923c723e26.png)

Error: `{csrf: {notSame: "The form submitted did not originate from expected site" }}`

The variable `window.csrf`was set successfully in the browser and it was sent to the server in the payload of the save request.

**Comment by inyono** [comment]
Things to check
- Is the CSRF token stable across different pods? e.g. when pod A renders the "form" (i.e. passes down the token via CSRF) but pod B gets the response, is the CSRF token the same? (pretty sure that is the case since AFAIK the Zend CSRF token is session-specific)
- The Zend CSRF token has a default timeout of 5 minutes. We should check whether we've already overridden the default. Not sure what the best practice is? Refreshing CSRF tokens? Longer timeout? If we still use the default value, we definitely need to do something since 5 mins is not enough for the editor.

**Comment by inyono** [comment]
Removed `edtr-io` label since I'm 99%-sure that the issue isn't in Edtr.io (we more or less pass `window.csrf` through) but rather in the token itself

**Comment by inyono** [comment]
Also: might have been handled in the old editor by default since a failing form would just have rerendered the form with the changes made (and maybe some obscure error message) but you could just resend it again (since rerendering refreshes the token).

**Comment by inyono** [comment]
Yep... The token is the problem. Sometimes getting different tokens in different tabs and they seem to expire. Might be related to our https://sentry.io/organizations/serlo/issues/1148109109/events/?project=1518832 issues...

**Comment by inyono** [comment]
Closed by #118
