### ISSUE TITLE
Notifications across language-versions raise page not found error

### ISSUE THREAD

**Issue by jakobwes** [serlo/serlo.org#173]
Notifications eg. when someone created a revision in an article in de.serlo.org (or any xy.serlo.org), still appear in other language tenants, but the links are not right (they are in the form xy.serlo.org/entity/view/id and raise a "page not found" error, while only using the form xy.serlo.org/id still redirects to the content)

**Comment by kulla** [comment]
Will be fixed by implementing https://github.com/serlo/api.serlo.org/issues/143

**Comment by elbotho** [comment]
@kulla before [implementing this](https://github.com/serlo/api.serlo.org/issues/143): are we sure, that we
- **a:** want to show notifications across instances? Sounds not very useful for anybody other than @jakobwes 
- **b** want to support links in the form of `/entity/view/:id` instead of just using /id instead?

**Comment by jakobwes** [comment]
@elbotho thanks for bringing this up! Of course I like features, that are solely developed for me (:wink:), but I also think this can actually be useful also for other people. We want in the LCU to also foster inter-language-collaboration on serlo.org with the goal of not having totally distinct and disconnected language-communities and have the possibility of language-version to be able to profit and get motivated from each other. For that it could be really useful (next to other tools like merging the edits in the profile-statistics) to have notifications across language-versions. Authors then wouldn't need to not need to check every language-version individually and if e.g. author A translates an article into Spanish, activates notifications, and there is fundamental revision on the article, because another didactical method is used, a notification on es.serlo.org would be useful. This isn't crucial, since you also get email-notifications, but it can be a nice addon (especially if it is easier to implement).

**Comment by elbotho** [comment]
okay, that solves a :)

**Comment by kulla** [comment]
The frontend should link to `/:id` or the actual current url (since you can get the instance and the alias from the api). This issue is for the legacy system and I have no idea where those links are set. So it's easier for us to support `/entity/view/:id` as an alias in the `uuid()` endpoint as we support `/user/profile/:id` there as well. After we have no legacy system in place any more and after we have no urls `/entity/view/:id` we can delete this feature.

**Comment by elbotho** [comment]
Thanks for your explanations!
