### ISSUE TITLE
unwanted frame around "Erklärung mit Multimedia Inhalt"

### ISSUE THREAD

**Issue by kathongi** [serlo/serlo.org#236]
![image](https://user-images.githubusercontent.com/44167220/72719255-c4601680-3b77-11ea-8003-77a9174379c7.png)

**Comment by kathongi** [comment]
http://de.serlo.org/141975

**Comment by Knorrke** [comment]
Thanks!

If someone wants to fix this: This happens, because the first slate instance gains focus (in redux store) for some reason, even though the editor is in render mode. So quick fix would be bluring the renderer after the initAction, but we probably should think about using a different store (or don't use redux at all) in the Renderer.

**Comment by inyono** [comment]
Closed upstream (deployment pending)
