### ISSUE TITLE
Notifications seem broken

### ISSUE THREAD

**Issue by Knorrke** [serlo/serlo.org#32]
There seems to be a problem with notifications since ~28.7.

**Comment by inyono** [comment]
Confirmed. Notification worker doesn't work in production right now. Had to create the notifications locally via Cloud SQL Proxy... Probably need to prioritize https://github.com/serlo/athene2/pull/853 higher, so that Notifications aren't depended on the worker. And provide a working worker for emails (session gc works for some reason, I don't know)...
