### ISSUE TITLE
Remove SC exercises

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#347]
In order to simplify the workflow for authors, we do not neet any distinction between SC and MC exercises any longer. Hence automatically every such exercise should be a MC one in future.

**Comment by inyono** [comment]
Isn't that already the case for the plugin in the new editor? Or what do you mean?

**Comment by yolo-bird** [comment]
Both options are still available:
![Screenshot_2020-03-31 Eine Auswahlaufgabe erstellen](https://user-images.githubusercontent.com/46370375/78008772-5d619980-7340-11ea-9a38-a3f1b22ce5af.png)

**Comment by yolo-bird** [comment]
But you are right: Multiple Choice is the default option.

**Comment by inyono** [comment]
Okay, this is what you mean. This is intentionally, because there also a difference for the learner on how to approach the exercise
- In sc exercises, the learner knows that there is only one correct choice. So a procedure of exclusion is a valid approach
- This is not the case for mc exercises because the learner doesn't know how many - if any - choices are correct

This is also indicated by the typical UX that is common in web: sc exercises are rendered with radio buttons (circles), mc exercises with checkboxes (squares).
