### ISSUE TITLE
Show badges also in rocket chat

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#381]

**Comment by kulla** [comment]
I have investigated this issue. We can set the following attributes of an user via the API:

![2021-03-10-152753_641x478_scrot](https://user-images.githubusercontent.com/1327215/110644294-3dc02b80-81b5-11eb-818a-9bbcab9f44d1.png)

However in the group chat they are not visible:

![2021-03-10-152853_1162x97_scrot](https://user-images.githubusercontent.com/1327215/110644400-5597af80-81b5-11eb-82e2-463c98ec6f33.png)

There is only a speak bubble visible next to the use when "status" is set. The properties are only visible when somebody clicks on the user:

![2021-03-10-152155_492x321_scrot](https://user-images.githubusercontent.com/1327215/110644502-7233e780-81b5-11eb-8c06-552a1bf569da.png)

Or when he / she sees the full profile:

![2021-03-10-152140_355x854_scrot](https://user-images.githubusercontent.com/1327215/110644556-824bc700-81b5-11eb-8545-2e43ba2b6b10.png)

So it is possible to show badges, however they are hidden and not directly visible. There are two workarounds available:

1) Add badges to avatar picture: might be hard to program
2) Add badges to username: I wouldn't advise this since we want the serlo and the rocket chat username to be the same.

**Comment by simonkoehl** [comment]
OK. Thank you very much for having a look at this! So I guess we close the issue..
