### ISSUE TITLE
Feedback of sc-mc-exercises sometimes not focusable

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#39]
E.g. https://de.serlo.org/entity/repository/add-revision/142516.

I assume that this is because something went wrong when converting? Not sure though. Focusing in https://demo.edtr.io works correctly.

**Comment by inyono** [comment]
On second thought: probably because of the preview... -.-

**Comment by Knorrke** [comment]
Looking into this right now. The problem is that the converter passes feedback and content as rows plugin to the sc-mc-exercise answers. This way our "is my child focused?" logic doesnt work.
I will create a fix for the converter, but that will break with old content that uses more then one plugin as content or feedback
