### ISSUE TITLE
Broken taxonomy

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#421]
on https://de.serlo.org/mathe/zahlen-gr%C3%B6%C3%9Fen/grundrechenarten the link "Aufgaben Rechengesetze und Rechentricks der Addition" is broken

**Comment by kulla** [comment]
I had created this taxonomy element during a session with an author when there was a bug with the new API. Thus I guess we have created a broken taxonomy element (I remember we couldn't use this taxonomy element well). I have deleted it which should solve this issue. Since I reported the bug that day and I cannot remember that other taxonomy elements were created that time, this should solve the issue.
