### ISSUE TITLE
Upload of workfiles for authors

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#426]
Author can upload for example xcf files for gimp, ggb files for Geogebra or word dokuments when uploading a pdf as an image. This enables an easy modification of the corresponding files.

**Comment by inyono** [comment]
Might combine that with the source stuff. We could actually require users to either:
- provide a link to the original source + license information (for external stuff).
- upload the source file to indicate that it was their own work.

Open questions:
- Would this approach always work? Or are there cases where there isn't really a source file? (e.g. photos: might still make sense to upload the image in original quality while we might optimize the file size of the image that we deliver to learners)
- Which file types do we allow? E.g. Word is a little bit problematic IMHO, since it is not an Open Source format (though we might avoid this specific issue by converting it to ODF instead). Adobe Photoshop / Illustrator would be another problem.

**Comment by kulla** [comment]
Open questions for me:

* How should the workflow / UX be?
* The source file and the actual image should always match. How can we enforce this?
    * Idea: Image can be an entity by itself so that we have pages for an image with all meta information like on https://commons.wikimedia.org/ (e.g. https://commons.wikimedia.org/wiki/File:Example_for_addition_of_functions.svg )
* Geogebratube already allows the download of the ggb file. Thus I guess this is not needed, right?

**Comment by inyono** [comment]
> How should the workflow / UX be?
> The source file and the actual image should always match. How can we enforce this? 

IMHO: this should probably be part of the image plugin. Author uploads original file and maybe adds some metadata (e.g. license information). Upload goes through our server (as done currently), server creates those file in GCS and passes it down to the editor, e.g.
```
originalFile: {}...
optimizedForMobile: {}...
optimizedForWhatever: {}...
```
In the Editor, you can download the original file. During rendering, we only use the optimized variants.

**Comment by yolo-bird** [comment]
Moved to https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
