### ISSUE TITLE
Allow formulas in spoiler heading

### ISSUE THREAD

**Issue by kathongi** [serlo/serlo.org#619]
We need formulas in spoiler headings for subjects like math, chemistry and physics. At the moment it's only possible to write text in the heading.

**Comment by kulla** [comment]
> Is this a frontend or edtr issue?

Oh, I am sorry, I missed that it needs to be implemented in edtr.io first. Thus I have transfered it back to serlo.org.

**Comment by kulla** [comment]
> @yolo-bird what do you think? It's rather a small bug fix than an interesting feature for authors.

It's not a small bug fix. I guess I might take me at least ~1 week to implement it in edtr.io. Thus I am with @Entkenntnis that you need to discuss when it shall be included on the software roadmap.

**Comment by kathongi** [comment]
@kulla Sorry. Bad wording. I never meant that the issue is a "small bug fix" for you or other software developers. I meant that it is rather unimportant for authors. It's necessary to include the feature but it's not like every author is keen on getting updates about it. Most of the authors probably don't even know that the problem exists. So maybe we don't need to put it on our trelloboard. That was my point.

**Comment by kulla** [comment]
> Most of the authors probably don't even know that the problem exists. So maybe we don't need to put it on our trelloboard.

My opinion: When it is not important enough to put it on the Trelloboard, than we should not implement this feature...

**Comment by kulla** [comment]
> > Most of the authors probably don't even know that the problem exists. So maybe we don't need to put it on our trelloboard.
> 
> My opinion: When it is not important enough to put it on the Trelloboard, than we should not implement this feature...

**Comment by kathongi** [comment]
> > Most of the authors probably don't even know that the problem exists. So maybe we don't need to put it on our trelloboard.
> 
> My opinion: When it is not important enough to put it on the Trelloboard, than we should not implement this feature...

In my opinion it's still important even if many authors won't need it. For me it's a basic feature. We have enough articles where formulas are used in spoiler headings which we can't convert properly and we will have many more use cases in the future --> we need it.

**Comment by Entkenntnis** [comment]
I would like to clearify that a "no" by the dev team does not mean that we think a feature is not useful or not important.

We say "no" mainly because we are restraint by our capacities. Which means that we have to say "no" even to feature that are actually important - that's not easy to do, also for us. And it's nothing that we are doing lightly.

That's the reason why I would prefer discussing feature requests in the trelloboard: It makes clear that features have to compete against each other and often, less important features will lose.

But we are also an open-source project, which means that (at least in theory), community software developers can add features that the main team can't focus on right now.

**Comment by CarolinJaser** [comment]
Moved to Google Doc https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
