### ISSUE TITLE
license notice in edtr.io missing for for content under other licenses

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#624]
E.g. serlo.org/11199: 
If I edit the content, before saving the usual text about agreeing to the terms is missing, but you still have the mark the checkbox.
![Screenshot_2021-04-28 Serlo – Die freie Lernplattform](https://user-images.githubusercontent.com/46370375/116377543-9608c680-a811-11eb-906a-4ec04cab5cb5.png)

Normally this text appears 
![Screenshot_2021-04-28 Serlo – Die freie Lernplattform(1)](https://user-images.githubusercontent.com/46370375/116377843-e2540680-a811-11eb-9084-a1e7c6bce092.png)

For the example mentioned above parts of the exercise is not licensed under our standard license. May that be the reason?

**Comment by inyono** [comment]
Not sure if this is the case here, but: this usually happens, when the license itself doesn't have a license text attached (which is often the case for non-CC licenses because someone only created them without adding some description). If so, we should add a description for those licenses, we have in use. We might be able to add a fallback if necessary (something like "this content is licensed under foo. Don't edit if you don't know what this entails)

**Comment by yolo-bird** [comment]
Thanks for the explanation. I just found the corresponding field in the license backend where to add the description. Therefore I will close the issue again.
